// Copyright (c) 2017, 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: microprofile-rest-client-async
:page-layout: guide-multipane
:page-duration: 15 minutes
:page-releasedate: 2019-07-05
:page-guide-category: microprofile
:page-essential: false
:page-description: Learn how to use MicroProfile Rest Client to invoke RESTful microservices over HTTP asynchronously.
:page-seo-title: Consuming REST services asynchronously
:page-seo-description: A tutorial on how to consume REST services asynchronously with MicroProfile Rest Client.
:guide-author: Open Liberty
:page-tags: ['MicroProfile', 'Java EE']
:page-permalink: /guides/{projectid}
:page-related-guides: ['microprofile-rest-client']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
= Consuming RESTful services asynchronously

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Learn how to use MicroProfile Rest Client to invoke RESTful microservices over HTTP asynchronously.

== What you'll learn

You will learn how to build a MicroProfile Rest Client to access remote RESTful services using asynchronous method calls. You'll update a template interface that maps to the remote service that you want to call. You'll change it to use a `CompletionStage` return type making the method asynchronous.

The application that you will be working with is an `inventory` service,
which stores the information about various JVMs that run on different systems.
Whenever a request is made to the `inventory` service to retrieve the JVM
system properties of a particular host, the `inventory` service communicates with the `system`
service on that host to get these system properties. The system properties are then stored and returned.

The implementations of the application and its services are provided for you in the `start/src` directory.
The `system` service can be found in the `start/src/main/java/io/openliberty/guides/system` directory, 
and the `inventory` service can be found in the `start/src/main/java/io/openliberty/guides/inventory` directory. 

If you are not too familiar with MicroProfile Rest Client, then read the https://openliberty.io/guides/microprofile-rest-client.html[Consuming RESTful services with template interfaces^] guide to learn more about it.

=== What is asynchronous programming?

Asynchronous programming can be thought of as a take-out restaurant. After ordering at the register and paying for your food, you’ll usually receive an order number. While your food is being prepared, you can leave the line and wait on the side. Once your order is ready, as indicated by your number being called, you can pick up your food. Your request for food has now been fulfilled. However, in a synchronous model, you would place your order and continue waiting in line at the counter, while blocking other customers from placing their order.

Asynchronous methods allow you to perform a lengthy operation, such as IO asynchronously. This means that the IO occurs in the background and the caller is notified via a callback to continue with their computation once it’s complete. The benefit is that this frees up the original thread to handle other work rather than waiting on IO to complete. Going back to the restaurant analogy, calling the `prepareFood()` method asynchronously frees up the person at the register. Since they're free, the person can take more orders from their line as they've been freed up from the responsibility of serving the previous person until their order is ready.

In the context of MicroProfile REST client, making HTTP requests can be a time consuming process. The network may be slow, or maybe the upstream service is overwhelmed and can't respond in a timely manner. These lengthy operations can block the execution of your thread when it's in use and prevent other work from being completed.

// =================================================================================================
// Getting started
// =================================================================================================

[role='command']
include::{common-includes}/gitclone.adoc[]

=== Try what you'll build

The `finish` directory in the root of this guide contains the finished inventory application. Give it a try before you proceed.

To try out the application, first navigate to the `finish` directory and then run the following
Maven goals to build the application and run it inside Open Liberty:

[role='command']
```
cd finish
mvn install liberty:start-server
```

Point your browser to the http://localhost:9080/inventory/systems[http://localhost:9080/inventory/systems^] URL. This is the starting point of the `inventory`
service and it displays the current contents of the inventory. As you might expect, these are empty since
nothing is stored in the inventory yet. Next, point your browser to the http://localhost:9080/inventory/systems/localhost[http://localhost:9080/inventory/systems/localhost^] URL.
You see a result in JSON format with the system properties of your local JVM. When you visit this URL, these system
properties are automatically stored in the inventory. Go back to http://localhost:9080/inventory/systems[http://localhost:9080/inventory/systems^] and
you see a new entry for `localhost`. For simplicity, only the OS name and user name are shown here for
each host. You can repeat this process for your own host name or any other machine that is running
the `system` service.

After you are done checking out the application, stop the Open Liberty server:

[role='command']
```
mvn liberty:stop-server
```

== Changing the template interface to use asynchronous methods

Navigate to the `start` directory to begin.

First, you will replace the system client interface to make the methods asynchronous.

[role="code_command hotspot", subs="quotes"]
----
#Replace the `SystemClient` interface.#
`src/main/java/io/openliberty/guides/inventory/client/SystemClient.java`
----
SystemClient.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/java/io/openliberty/guides/inventory/client/SystemClient.java[]
----

The only change is that the [hotspot=getProperties file=0]`getProperties()` method now returns `CompletionStage<Properties>` instead of `Properties`. This change makes the method asynchronous. Since the method now has a return type of `CompletionStage<Properties>`, you will not be able to directly manipulate the `Properties` object. As you will see in the next section, you will be able to indirectly use the `Properties` object by chaining callbacks.

== Responding asynchronously to an HTTP request

JAX-RS resources can also have asynchronous methods. So instead of returning a `Response` type, you may return a `CompletionStage<Response>` type. Completion stages can be chained together using the [hotspot=thenApplyAsync file=0]`thenApplyAsync()` method, and exceptions can be handled using the [hotspot=exceptionally file=0]`exceptionally()` method.

[role="code_command hotspot", subs="quotes"]
----
#Replace the `InventoryResource` class.#
`src/main/java/io/openliberty/guides/inventory/InventoryResource.java`
----
InventoryResource.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/java/io/openliberty/guides/inventory/InventoryResource.java[]
----

Similar to the synchronous approach, if we successfully get the properties from the server running at a given host name, then the resource will respond with an HTTP status of 200 and the body will contain the system properties. If an exception occurs, then the response will have a 404 status and a body containing an error message. Finally, return the `CompletionStage<Response>` you built up using the [hotspot=thenApplyAsync file=0]`thenApplyAsync()` and [hotspot=exceptionally file=0]`exceptionally()` methods.

A completion stage represents a unit of computation. Once that computation completes, it can either be finished or chained with more completion stages using [hotspot=thenApplyAsync file=0]`thenApplyAsync()` to perform more computations. Exceptions can be handled in a callback provided to the [hotspot=exceptionally file=0]`exceptionally()` method, which functionally behaves similar to a catch block. When you return a completion stage in the resource, it doesn’t necessarily mean that the computation has completed and the response has been built. JAX-RS will respond to the caller once the `CompletionStage` has completed.

// =================================================================================================
// Building the application
// =================================================================================================

[role='command']
include::{common-includes}/mvnbuild.adoc[]

You can find the `inventory` and `system` services at the following URLs:

- http://localhost:9080/inventory/systems[http://localhost:9080/inventory/systems^]
- http://localhost:9080/system/properties[http://localhost:9080/system/properties^]

// =================================================================================================
// Testing
// =================================================================================================

== Testing the inventory application

A few tests are included for you to test the basic functionality of the microservices. If a test failure occurs, then you might have introduced a bug into the code. To run the tests, wait for all pods to be in the ready state before proceeding further. 

[role="code_command hotspot", subs="quotes"]
----
#Create the `InventoryEndpointTest` class.#
`src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointTest.java`
----

See the following descriptions of the test cases:

* [hotspot=testEmptyInventory file=0]`testEmptyInventory()` verifies that the inventory is initially empty when the server first starts up.

* [hotspot=testHostRegistration file=0]`testHostRegistration()` verifies that a host is correctly added to the inventory.

* [hotspot=testSystemPropertiesMatch file=0]`testSystemPropertiesMatch()` verifies that the JVM system properties returned by the `system` service match
the ones stored in the `inventory` service.

* [hotspot=testUnknownHost file=0]`testUnknownHost()` verifies that an unknown host or a host that does not expose their JVM system
properties is correctly handled as an error.

Finally, the [hotspot file=1]`SystemEndpointTest.java` file
is included for you to test the basic functionality of the `system` service.
It can be found under the `src/test/java/it/io/openliberty/guides/system/` directory.

InventoryEndpointTest.java
[source, Java, linenums, role='code_column hide_tags=copyright,javadoc']
----
include::finish/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointTest.java[]
----

SystemEndpointTest.java
[source, Java, linenums, role='code_column hide_tags=copyright,javadoc']
----
include::finish/src/test/java/it/io/openliberty/guides/system/SystemEndpointTest.java[]
----

// =================================================================================================
// Running the tests
// =================================================================================================

[role='command']
include::{common-includes}/mvnverify.adoc[]

When the tests succeed you will see output similar to the following.

[source, role='no_copy']
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.system.SystemEndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.99 sec - in it.io.openliberty.guides.system.SystemEndpointTest
Running it.io.openliberty.guides.inventory.InventoryEndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.325 sec - in it.io.openliberty.guides.inventory.InventoryEndpointTest

Results :

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
----

== Great work! You're done!

You have just completed building a simple inventory application by making asynchronous HTTP requests using Open Liberty.

include::{common-includes}/attribution.adoc[subs="attributes"]
