// Copyright (c) 2017, 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: microprofile-rest-client-async
:page-layout: guide-multipane
:page-duration: 15 minutes
:page-releasedate: 2019-07-05
:page-guide-category: microprofile
:page-essential: false
:page-description: Learn how to use MicroProfile Rest Client to invoke RESTful microservices over HTTP asynchronously.
:page-seo-title: Consuming REST services asynchronously
:page-seo-description: A tutorial on how to consume REST services asynchronously with MicroProfile Rest Client.
:guide-author: Open Liberty
:page-tags: ['MicroProfile', 'Java EE']
:page-permalink: /guides/{projectid}
:page-related-guides: ['microprofile-rest-client']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
:mac: Mac
:win: Windows
:linux: Linux
= Consuming RESTful services asynchronously

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Learn how to use MicroProfile Rest Client to invoke RESTful microservices over HTTP asynchronously.

== What you'll learn

You will learn how to build a MicroProfile Rest Client to access remote RESTful services using asynchronous method calls. You'll update a template interface that maps to the remote service that you want to call. You'll change it to use a `CompletionStage` return type making the method asynchronous. A completion stage is a class that will allow you to use the result of your remote service call at some point in the future.

=== What is asynchronous programming?

Asynchronous programming can be thought of as a take-out restaurant. After ordering at the register and paying for your food, you’ll usually receive an order number. While your food is being prepared, you can leave the line and wait on the side. Once your order is ready, as indicated by your number being called, you can pick up your food. Your request for food has now been fulfilled. However, in a synchronous model, you would place your order and continue waiting in line at the counter, while blocking other customers from placing their order.

Asynchronous methods allow you to perform a lengthy operation, such as IO asynchronously. This means that the IO occurs in the background and the caller is notified via a callback to continue with their computation once it’s complete. The benefit is that this frees up the original thread to handle other work rather than waiting on IO to complete. Going back to the restaurant analogy, calling the `prepareFood()` method asynchronously frees up the person at the register. Since they're free, the person can take more orders from their line as they've been freed up from the responsibility of serving the previous person until their order is ready.

In the context of MicroProfile REST client, making HTTP requests can be a time consuming process. The network may be slow, or maybe the upstream service is overwhelmed and can't respond quickly. These lengthy operations can block the execution of your thread when it's in use and prevent other work from being completed.

The application you will be working with is a job runner that mantains an inventory of available systems.
It consists of four microservices `bff`, `job`, `system`, and `inventory`.
The `job` microservices allows you to dispatch jobs that will be run by the `system` microservice.
The job is a sleep operation that lasts for a duration of 5 to 10 seconds. When it completes, the `system` microservice
publishes the sleep time as the result of this job. In addition to running jobs, the `system` microservice also registers
itself on startup with the `inventory` microservice that keeps track of all instances of the `system` microservice. Finally,
the `bff` microservice is a https://microservices.io/patterns/apigateway.html#variation-backends-for-frontends[backend for front end^].
It communicates with the backend `job` and `inventory` microservice on the caller's behalf.

The microservice that you will modify with is the `bff` service.
It acts as a gateway to communicate with the backend microservices.
Whenever a request is made to the `bff` service to retrieve the jobs
the `bff` service communicates with the `jobs`
service on that host to get the completed jobs.

The implementations of the application and its services are provided for you in the `start/src` directory.

If you are not too familiar with MicroProfile Rest Client, then read the https://openliberty.io/guides/microprofile-rest-client.html[Consuming RESTful services with template interfaces^] guide to learn more about it.


// =================================================================================================
// Getting started
// =================================================================================================

[role='command']
include::{common-includes}/gitclone.adoc[]

== Changing the template interface to use asynchronous methods

Navigate to the `start` directory to begin.

First, you will replace the job client interface to make the methods asynchronous.

[role="code_command hotspot", subs="quotes"]
----
#Replace the `JobClient` interface.#
`bff/src/main/java/io/openliberty/guides/bff/client/JobClient.java`
----
JobClient.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/bff/src/main/java/io/openliberty/guides/bff/client/JobClient.java[]
----

The changes involve changing the return types of the [hotspot=getJobs file=0]`getJobs`, [hotspot=getJob file=0]`getJob`, and [hotspot=createJob file=0]`createJob` methods to return `CompletionStage<T>` types. These changes make the methods asynchronous. Since the methods now have a return type of `CompletionStage<T>`, you won’t be able to directly manipulate the inner type. As you will see in the next section, you will be able to indirectly use the inner object by chaining callbacks.

== Responding asynchronously to an HTTP request

JAX-RS resources can also have asynchronous methods. So instead of returning a `JobsListModel` type, you may return a `CompletionStage<JobsListModel>` type. Completion stages can be chained together using the [hotspot=thenApplyAsync file=0]`thenApplyAsync()` method.

[role="code_command hotspot", subs="quotes"]
----
#Replace the `JobResource` class.#
`bff/src/main/java/io/openliberty/guides/bff/JobResource.java`
----
JobResource.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/bff/src/main/java/io/openliberty/guides/bff/JobResource.java[]
----

Similar to the synchronous approach, if we successfully get the completed jobs from the job microservice, then the resource will respond with an HTTP status of 200 and the body will contain a list of jobs. Finally, return the `CompletionStage<JobsListModel>` you built up using the [hotspot=thenApplyAsync file=0]`thenApplyAsync()`.

A completion stage represents a unit of computation. Once that computation completes, it can either be finished or chained with more completion stages using [hotspot=thenApplyAsync file=0]`thenApplyAsync()` to perform more computations. Exceptions can be handled in a callback provided to the `exceptionally()` method, which functionally behaves similar to a catch block. When you return a completion stage in the resource, it doesn’t necessarily mean that the computation has completed and the response has been built. JAX-RS will respond to the caller once the `CompletionStage` has completed.

// =================================================================================================
// Building the application
// =================================================================================================

== Building and running the application

To build the application, run the Maven `package` goal from the command line in the `start` directory.

[role='command']
```
mvn clean package
```

Next, use the provided script to start the application in docker containers.

****
[system]#*{linux} | {mac}*#

[role='command']
```
./scripts/start-app
```

[system]#*{win}*#

[role='command']
```
.\scripts\start-app.bat
```
****

You can access the application by making requests to the `bff` job endpoints.

- GET http://localhost:8080/api/jobs[http://localhost:8080/api/jobs^]
- GET http://localhost:8080/api/jobs/{jobId}
- POST http://localhost:8080/api/jobs[http://localhost:8080/api/jobs^]

Switching to an asynchronous programming model has freed up the thread handling your request to `/api/jobs`. While MicroProfile REST Client makes a request, the thread can handle other work.

// =================================================================================================
// Testing
// =================================================================================================

== Testing the bff application

A few tests are included for you to test the basic functionality of the `bff` microservice. If a test failure occurs, then you might have introduced a bug into the code.

[role="code_command hotspot", subs="quotes"]
----
#Create the `JobEndpointTest` class.#
`bff/src/test/java/it/io/openliberty/guides/bff/JobEndpointTest.java`
----

See the following descriptions of the test cases:

* [hotspot=testCreateJob file=0]`testCreateJob()` verifies that the bff service communicates with a backend service to create a job.

* [hotspot=testGetJobs file=0]`testGetJobs()` verifies that the bff service communicates with an upstream service to get all jobs and transforms them appropriately to a `JobListModel`.

JobEndpointTest.java
[source, Java, linenums, role='code_column hide_tags=copyright,javadoc']
----
include::finish/bff/src/test/java/it/io/openliberty/guides/bff/JobEndpointTest.java[]
----

// =================================================================================================
// Running the tests
// =================================================================================================

=== Running the tests

Navigate to the `bff` directory, then verify that the tests pass using the Maven `verify` goal:

[role='command']
```
mvn verify -Ddockerfile.skip
```

When the tests succeed you will see output similar to the following.

[source, role='no_copy']
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.bff.InventoryEndpointTest
Failed to load class "org.slf4j.impl.StaticLoggerBinder".
Defaulting to no-operation (NOP) logger implementation
See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.88 s - in it.io.openliberty.guides.bff.InventoryEndpointTest
Running it.io.openliberty.guides.bff.JobEndpointTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.455 s - in it.io.openliberty.guides.bff.JobEndpointTest

Results:

Tests run: 4, Failures: 0, Errors: 0, Skipped: 0
----

== Teardown

Navigate back to the `start` directory.

Finally, use the provided script to stop the application.

****
[system]#*{linux} | {mac}*#

[role='command']
```
./scripts/stop-app
```

[system]#*{win}*#

[role='command']
```
.\scripts\stop-app.bat
```
****

== Great work! You're done!

You have just completed modifying an application to make asynchronous HTTP requests using Open Liberty.

include::{common-includes}/attribution.adoc[subs="attributes"]
